/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicNiveauTjekRouteImport } from './routes/api/public/niveau-tjek'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNiveauTjekRoute = ApiPublicNiveauTjekRouteImport.update({
  id: '/api/public/niveau-tjek',
  path: '/api/public/niveau-tjek',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/niveau-tjek': typeof ApiPublicNiveauTjekRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/niveau-tjek': typeof ApiPublicNiveauTjekRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/niveau-tjek': typeof ApiPublicNiveauTjekRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/niveau-tjek'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/niveau-tjek'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/public/contact'
    | '/api/public/lead'
    | '/api/public/niveau-tjek'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicNiveauTjekRoute: typeof ApiPublicNiveauTjekRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/niveau-tjek': {
      id: '/api/public/niveau-tjek'
      path: '/api/public/niveau-tjek'
      fullPath: '/api/public/niveau-tjek'
      preLoaderRoute: typeof ApiPublicNiveauTjekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicNiveauTjekRoute: ApiPublicNiveauTjekRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
